FROM python:3.10-slim

WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY data /app/data
COPY src /app/src

# Set environment variables
ENV PYTHONPATH /app
ENV FLASK_APP src/app.py
ENV FLASK_ENV development
ENV PORT 5000

# Expose port
EXPOSE 5000

# Run the application
CMD ["python", "src/app.py"] 